-- QUERY 3G con comuna y región
SELECT 
  EXTRACT(ISOWEEK FROM PARSE_DATE('%Y%m%d', CAST(H.ID_DWH_DIA AS STRING))) AS SEMANA,
  C.SITIO,
  UPPER(COM.NOMBRE_COMUNA) AS COMUNA,
  UPPER(REG.DESC_CORTA3) AS REGION,
  '3G' AS RAT,
  SUM(VS_HSUPA_MEANCHTHROUGHPUT_TOTALMBYTES / 1024) AS UL_Traffic_3G_GB,
  SUM(VS_HSDPA_MEANCHTHROUGHPUT_TOTALMBYTES / 1024) AS DL_Traffic_3G_GB,
  SUM((VS_HSDPA_MEANCHTHROUGHPUT_TOTALMBYTES + VS_HSUPA_MEANCHTHROUGHPUT_TOTALMBYTES) / 1024) AS Total_Traffic_3G_GB
FROM 
  wom-edms-prod-d6d5.STG_TRAF.MAE_3G_CELL_COUNTERS_HOUR AS H
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_ANTENAS AS C
  ON NODEBNAME= C.NODO
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_COMUNAS AS COM
  ON C.ID_COMUNA = COM.ID_COMUNA
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_REGIONES AS REG
  ON REG.ID_REGION = COM.ID_REGION
WHERE 
  H.ID_DWH_DIA BETWEEN 20250721 AND 20250727
GROUP BY 
  SEMANA, C.SITIO, COMUNA, REGION
ORDER BY 
  C.SITIO ASC;


--- QUERY 4G con comuna y región
SELECT 
  EXTRACT(ISOWEEK FROM PARSE_DATE('%Y%m%d', CAST(H.ID_DWH_DIA AS STRING))) AS SEMANA,
  C.SITIO,
  UPPER(COM.NOMBRE_COMUNA) AS COMUNA,
  UPPER(REG.DESC_CORTA3) AS REGION,
  '4G' AS RAT,
  SUM(L_Thrp_bits_UL / (1024*1024*1024*8)) AS UL_Traffic_4G_GB,
  SUM(L_Thrp_bits_DL / (1024*1024*1024*8)) AS DL_Traffic_4G_GB,
  SUM((L_Thrp_bits_DL + L_Thrp_bits_UL) / (1024*1024*1024*8)) AS Total_Traffic_4G_GB
FROM 
  wom-edms-prod-d6d5.STG_TRAF.MAE_4G_CELL_COUNTERS_HOUR AS H
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_ANTENAS AS C
  ON SPLIT(H.NODE, '-')[SAFE_OFFSET(1)] = C.SITIO
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_COMUNAS AS COM
  ON C.ID_COMUNA = COM.ID_COMUNA
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_REGIONES AS REG
  ON REG.ID_REGION = COM.ID_REGION
WHERE 
  H.ID_DWH_DIA BETWEEN 20250721 AND 20250727
GROUP BY 
  SEMANA, C.SITIO, COMUNA, REGION
ORDER BY 
  C.SITIO ASC;


-- QUERY 5G con comuna y región
SELECT 
  EXTRACT(ISOWEEK FROM PARSE_DATE('%Y%m%d', CAST(ID_DWH_DIA AS STRING))) AS SEMANA,
  C.SITIO,
  UPPER(COM.NOMBRE_COMUNA) AS COMUNA,
  UPPER(REG.DESC_CORTA3) AS REGION,
  '5G' AS RAT,
  SUM(N_ThpVol_UL / (810241024)) AS UL_Traffic_5G_GB,
  SUM(N_ThpVol_DL / (810241024)) AS DL_Traffic_5G_GB,
  SUM((N_ThpVol_DL + N_ThpVol_UL) / (810241024)) AS Total_Traffic_5G_GB
FROM 
  wom-edms-prod-d6d5.STG_TRAF.MAE_5G_CELL_COUNTERS_HOUR AS H
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_ANTENAS AS C
  ON    SPLIT(H.NODE, '-')[SAFE_OFFSET(1)]  = C.SITIO  
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_COMUNAS AS COM
  ON C.ID_COMUNA = COM.ID_COMUNA
LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_GEO_REGIONES AS REG
  ON REG.ID_REGION = COM.ID_REGION
WHERE 
  ID_DWH_DIA BETWEEN 20250721 AND 20250727
GROUP BY 
  SEMANA, C.SITIO, COMUNA, REGION
ORDER BY 
  C.SITIO ASC;
