## Query Diario - Uptime por día
SELECT 
  DATEID,
  (1 - SUM(NUMERADOR) / SUM(DENOMINADOR)) * 100 AS UPTIME_PORCENTAJE
FROM (
  SELECT
    ID_DWH_DIA AS DATEID,
    SUM(SEGUNDOS_INCIDENCIAS) AS NUMERADOR,
    SUM(SITIOS_ON_AIR) * 86400 AS DENOMINADOR
  FROM `wom-edms-prod-d6d5.STG_TRAF.BT_NET_UPTIME_INCIDENCIAS_RED_DIA`
  GROUP BY ID_DWH_DIA
) AS UP
GROUP BY DATEID

## Query Semanal - Uptime por semana y región
SELECT 
  YEARID,
  WEEKID,
  REGION,
  (1 - SUM(NUMERADOR) / SUM(DENOMINADOR)) * 100 AS UPTIME_PORCENTAJE
FROM (
  SELECT
    ID_DWH_AGNO AS YEARID,
    ID_DWH_SEMANA AS WEEKID,
    NE_REGION AS REGION,
    SUM(SEGUNDOS_INCIDENCIAS) AS NUMERADOR,
    SUM(SITIOS_ON_AIR) * 86400 * 7 AS DENOMINADOR
  FROM `wom-edms-prod-d6d5.STG_TRAF.BT_NET_UPTIME_INCIDENCIAS_RED_SEMANA`
  GROUP BY ID_DWH_AGNO, ID_DWH_SEMANA, NE_REGION
) AS UP
GROUP BY YEARID, WEEKID, REGION
