--Q_objetivo_Activo

SELECT 
obj.DESC_OBJETIVO_COMERCIAL
,count(distinct HR.NUMERO_ABONADO) as Q_abo

FROM wom-edms-prod-d6d5.STG_TRAF.AGG_TRF_DATOS_ABONADO_HORA AS HR
  LEFT JOIN wom-edms-prod-d6d5.DWH_WOM.LK_TPO_DIA AS DIA ON HR.ID_DWH_DIA = DIA.ID_DWH_DIA
  left join `wom-edms-prod-d6d5.DWH_WOM.BT_CLE_PARQUE` as PM
on HR.NUMERO_ABONADO = PM.NUMERO_ABONADO

left join  `wom-edms-prod-d6d5.DWH_WOM.LK_PLN_PLAN` as PLN on PLN.ID_PLAN =PM.ID_PLAN
left join `wom-edms-prod-d6d5.DWH_WOM.LK_PLN_OBJETIVO_COMERCIAL_PLAN` as obj on obj.ID_OBJETIVO_COMERCIAL = PLN.ID_OBJETIVO_COMERCIAL
--left join `wom-edms-prod-d6d5.DWH_WOM.LK_PLN_SEGMENTO_PLAN` as seg on seg.ID_SEGMENTO_PLAN = obj.ID_SEGMENTO_PLAN
  
WHERE DIA.ID_DWH_DIA BETWEEN 20250701 AND 20250731

and PM.FLAG_PARQUE = 1 
and PM.PERIODO_PARQUE = 202507
GROUP BY 1
